name: Deploy Docs to github.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build docs app
        run: |
          cd apps/docs
          pnpm build

      - name: Clone github.io repo
        run: |
          git clone https://github.com/kimdw524/kimdw524.github.io.git out

      - name: Prepare target branch
        run: |
          cd out
          git fetch
          git checkout react-kits || git checkout -b react-kits

          mkdir -p dist
          rm -rf dist/*

      - name: Copy build output into dist/
        run: |
          cp -r apps/docs/public/* out/dist/

      - name: Commit & Push
        run: |
          cd out
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Deploy docs from react-kits" || echo "No changes"
          git push https://$GH_PAGES_TOKEN@github.com/kimdw524/kimdw524.github.io.git react-kits

    env:
      GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
