name: main

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9.0.0

jobs:
  test-and-version-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get changed packages
        id: changed
        run: |
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '^packages/' | cut -d/ -f2 | sort | uniq | tr '\n' ' ')
          echo "changed_packages=$CHANGED" >> $GITHUB_OUTPUT

      - name: Bump changed packages
        if: ${{ steps.changed.outputs.changed_packages }}
        run: |
          set -e
          for pkg in ${{ steps.changed.outputs.changed_packages }}; do
            COMMITS=$(git log ${{ github.event.before }}..${{ github.sha }} --pretty=%B -- packages/$pkg || true)
            echo $pkg
            if echo "$COMMITS" | grep -q '^feat'; then
              pnpm --filter $pkg exec pnpm version minor
            else
              pnpm --filter $pkg exec pnpm version patch
            fi
          done


      - name: commit
        if: ${{ steps.changed.outputs.changed_packages }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: bump package versions"
          git push

      # - name: Publish changed packages
      #   if: ${{ steps.changed.outputs.changed_packages }}
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     for pkg in ${{ steps.changed.outputs.changed_packages }}; do
      #       pnpm --filter $pkg publish --access public
      #     done
